# Generated by Django 4.2.1 on 2023-06-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.category')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_core.currencytype')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerType', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_products', models.CharField(blank=True, max_length=10)),
                ('total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_core.category')),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.products')),
            ],
        ),
        migrations.CreateModel(
            name='productStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.products')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('id_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.equipment_category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('customer_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.typecustomer')),
            ],
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNumber', models.CharField(max_length=20, unique=True)),
                ('billItems', models.ManyToManyField(to='API_core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNumber', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=500)),
                ('phoneNumber', models.CharField(blank=True, max_length=9)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateField()),
                ('billItems', models.ManyToManyField(to='API_core.sale')),
                ('bill_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.bill_state')),
                ('currency_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_core.currencytype')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.typecustomer')),
                ('id_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.month')),
                ('id_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.year')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_core.paymenttype')),
            ],
        ),
    ]
