# Generated by Django 4.2.1 on 2023-06-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub_total', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.category')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_products', models.IntegerField()),
                ('price_at_moment', models.FloatField()),
                ('total_sale', models.FloatField()),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.bill')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.products')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.equipment_category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=10)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.typecustomer')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_bill_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.bill_state'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_currency_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_core.currencytype'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.month'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_core.paymenttype'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.year'),
        ),
    ]
