# Generated by Django 4.2.1 on 2023-05-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Stock',
            new_name='stock',
        ),
    ]
