# Generated by Django 4.2.1 on 2023-06-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0002_alter_billitems_billnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_products',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_at_moment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sale',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
