# Generated by Django 4.2.1 on 2023-05-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0002_rename_cost_products_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=50)),
                ('sub_total', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_products', models.IntegerField()),
                ('price_at_moment', models.FloatField()),
                ('total_sale', models.FloatField()),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.bill')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.products')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.equipment_category')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='id_bill_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.bill_state'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.month'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.year'),
        ),
        migrations.AddField(
            model_name='products',
            name='id_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='API_core.category'),
            preserve_default=False,
        ),
    ]
