# Generated by Django 4.2.1 on 2023-06-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0003_alter_sale_amount_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='price_at_moment',
            new_name='price',
        ),
    ]
