# Generated by Django 4.2.1 on 2023-05-21 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0004_typecustomer_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('simbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_core.customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_currency_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_core.currencytype'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_paymen_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API_core.paymenttype'),
        ),
    ]
