# Generated by Django 4.2.1 on 2023-06-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0004_rename_price_at_moment_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='stock',
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='productStock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productStock', to='API_core.products'),
        ),
    ]
