# Generated by Django 4.2.1 on 2023-06-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0005_remove_productstock_stock_products_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='productStock',
        ),
        migrations.AddField(
            model_name='productstock',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
