# Generated by Django 4.2.1 on 2023-05-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0006_rename_id_paymen_type_bill_id_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencytype',
            old_name='simbol',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='paymenttype',
            old_name='name',
            new_name='payment_type',
        ),
    ]
