# Generated by Django 4.2.1 on 2023-06-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0006_remove_products_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billItems',
            field=models.ManyToManyField(to='API_core.sale'),
        ),
    ]
