# Generated by Django 4.2.1 on 2023-06-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_core', '0007_bill_billitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
